
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceAmiscoLive", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://41.138.70.142:9997/datalive?wsdl")
public class ServiceAmiscoLive
    extends Service
{

    private final static URL SERVICEAMISCOLIVE_WSDL_LOCATION;
    private final static WebServiceException SERVICEAMISCOLIVE_EXCEPTION;
    private final static QName SERVICEAMISCOLIVE_QNAME = new QName("http://tempuri.org/", "ServiceAmiscoLive");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://41.138.70.142:9997/datalive?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEAMISCOLIVE_WSDL_LOCATION = url;
        SERVICEAMISCOLIVE_EXCEPTION = e;
    }

    public ServiceAmiscoLive() {
        super(__getWsdlLocation(), SERVICEAMISCOLIVE_QNAME);
    }

    public ServiceAmiscoLive(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEAMISCOLIVE_QNAME, features);
    }

    public ServiceAmiscoLive(URL wsdlLocation) {
        super(wsdlLocation, SERVICEAMISCOLIVE_QNAME);
    }

    public ServiceAmiscoLive(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEAMISCOLIVE_QNAME, features);
    }

    public ServiceAmiscoLive(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceAmiscoLive(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceAmiscoLive
     */
    @WebEndpoint(name = "AmiscoBinding_IServiceAmiscoLive")
    public IServiceAmiscoLive getAmiscoBindingIServiceAmiscoLive() {
        return super.getPort(new QName("http://tempuri.org/", "AmiscoBinding_IServiceAmiscoLive"), IServiceAmiscoLive.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceAmiscoLive
     */
    @WebEndpoint(name = "AmiscoBinding_IServiceAmiscoLive")
    public IServiceAmiscoLive getAmiscoBindingIServiceAmiscoLive(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "AmiscoBinding_IServiceAmiscoLive"), IServiceAmiscoLive.class, features);
    }

    /**
     * 
     * @return
     *     returns IServiceAmiscoLive
     */
    @WebEndpoint(name = "AmiscoBinding_IServiceAmiscoLive1")
    public IServiceAmiscoLive getAmiscoBindingIServiceAmiscoLive1() {
        return super.getPort(new QName("http://tempuri.org/", "AmiscoBinding_IServiceAmiscoLive1"), IServiceAmiscoLive.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceAmiscoLive
     */
    @WebEndpoint(name = "AmiscoBinding_IServiceAmiscoLive1")
    public IServiceAmiscoLive getAmiscoBindingIServiceAmiscoLive1(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "AmiscoBinding_IServiceAmiscoLive1"), IServiceAmiscoLive.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEAMISCOLIVE_EXCEPTION!= null) {
            throw SERVICEAMISCOLIVE_EXCEPTION;
        }
        return SERVICEAMISCOLIVE_WSDL_LOCATION;
    }

}
